# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mongo
    volumes:
    - datadb:/data/db
    - ./mongod.conf:/etc/mongod.conf
    ports:
    - "37017:27017"
    command: ["mongod", "--config", "/etc/mongod.conf", "--smallfiles", "--logpath=/dev/null"]
    container_name: db

  server:
    build: .
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

volumes:
  datadb:

